name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t ksleong/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ksleong/react-test npm test

      - run: docker build -t ksleong/multi-client ./client
      - run: docker build -t ksleong/multi-nginx ./nginx
      - run: docker build -t ksleong/multi-server ./server
      - run: docker build -t ksleong/multi-worker ./worker

      - run: docker push ksleong/multi-client
      - run: docker push ksleong/multi-nginx
      - run: docker push ksleong/multi-server
      - run: docker push ksleong/multi-worker
